### ISSUE TITLE
[Client] Application Styles 

### ISSUE THREAD

**Issue by Pseipel** [codeschluss/wupportal#15] opened 2018-03-18 09:19 UTC
Das Aussehen der App wird noch verändert werden.

**Comment by vetemi** [comment] 2018-04-27 13:46
- Buttonfarben
- Navbarlink
- Footer am Ende

**Comment by schlusslicht** [comment] 2018-11-26 18:14
This seems to be a dupe of https://github.com/codeschluss/wupportal/issues/66. Can it be closed, as https://github.com/codeschluss/wupportal/commit/b9f26cbda8415acf97ed15879be4f685e66c3959 was merged?

**Comment by schlusslicht** [comment] 2019-09-25 08:34
Done.

**Closed by schlusslicht** 2019-09-25 08:34 UTC
Labels: enhancement
